auto_scale_lr = dict(base_batch_size=16, enable=False)
backend_args = None
class_name = (
    'hole',
    'leaf-opex',
    'corrosion',
    'stain',
    'corrosion-pit',
    'lightning-arrester-miss',
    'degumming',
    'repair',
    'lightning-arrester',
    'teeth',
    'demould',
    'painting-peel-off',
    'sign',
    'crack',
    'dirt',
    'swell',
    'oil',
)
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'mmdet.models.dense_heads.gfocal_head',
    ])
data_root = '../WindBlade-30K/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        interval=1,
        max_keep_ckpts=1,
        rule='greater',
        save_best='coco/bbox_mAP',
        save_last=True,
        type='CheckpointHook'),
    logger=dict(interval=10, log_metric_by_epoch=False, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = 'runs/windturbine_GFLv2/KURGFl/best_coco_bbox_mAP_epoch_10.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
max_epochs = 36
metainfo = dict(
    classes=(
        'hole',
        'leaf-opex',
        'corrosion',
        'stain',
        'corrosion-pit',
        'lightning-arrester-miss',
        'degumming',
        'repair',
        'lightning-arrester',
        'teeth',
        'demould',
        'painting-peel-off',
        'sign',
        'crack',
        'dirt',
        'swell',
        'oil',
    ),
    palette=[
        (
            220,
            20,
            60,
        ),
        (
            119,
            11,
            32,
        ),
        (
            0,
            0,
            142,
        ),
        (
            0,
            0,
            230,
        ),
        (
            106,
            0,
            228,
        ),
        (
            0,
            60,
            100,
        ),
        (
            0,
            80,
            100,
        ),
        (
            0,
            0,
            70,
        ),
        (
            0,
            0,
            192,
        ),
        (
            250,
            170,
            30,
        ),
        (
            100,
            170,
            30,
        ),
        (
            220,
            220,
            0,
        ),
        (
            175,
            116,
            175,
        ),
        (
            250,
            0,
            30,
        ),
        (
            165,
            42,
            42,
        ),
        (
            255,
            77,
            255,
        ),
        (
            255,
            77,
            144,
        ),
    ])
model = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(checkpoint='torchvision://resnet50', type='Pretrained'),
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='pytorch',
        type='ResNet'),
    bbox_head=dict(
        anchor_generator=dict(
            octave_base_scale=4,
            ratios=[
                1.0,
            ],
            scales_per_octave=1,
            strides=[
                8,
                16,
                32,
                64,
                128,
            ],
            type='AnchorGenerator'),
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=2.0, reduction='mean', type='GIoULoss'),
        loss_cls=dict(
            beta=2.0,
            loss_weight=1.0,
            type='QualityFocalLoss',
            use_sigmoid=False),
        loss_dfl=dict(loss_weight=0.25, type='DistributionFocalLoss'),
        num_classes=17,
        reg_channels=64,
        reg_max=16,
        reg_topk=4,
        stacked_convs=4,
        type='GFocalHead'),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        add_extra_convs='on_output',
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=5,
        out_channels=256,
        start_level=1,
        type='FPN'),
    test_cfg=dict(
        max_per_img=300,
        min_bbox_size=0,
        nms=dict(iou_threshold=0.4, type='nms'),
        nms_pre=1000,
        score_thr=0.001),
    train_cfg=dict(
        allowed_border=-1,
        assigner=dict(topk=9, type='ATSSAssigner'),
        debug=False,
        initial_epoch=40,
        pos_weight=-1),
    type='GFL')
num_classes = 17
optim_wrapper = dict(
    clip_grad=None,
    loss_scale='dynamic',
    optimizer=dict(lr=0.005, momentum=0.9, type='SGD', weight_decay=0.0001),
    paramwise_cfg=dict(
        custom_keys=dict(
            hybrid_linear_weight=dict(decay_mult=0.0, lr_mult=0.05))),
    type='AmpOptimWrapper')
palette = [
    (
        220,
        20,
        60,
    ),
    (
        119,
        11,
        32,
    ),
    (
        0,
        0,
        142,
    ),
    (
        0,
        0,
        230,
    ),
    (
        106,
        0,
        228,
    ),
    (
        0,
        60,
        100,
    ),
    (
        0,
        80,
        100,
    ),
    (
        0,
        0,
        70,
    ),
    (
        0,
        0,
        192,
    ),
    (
        250,
        170,
        30,
    ),
    (
        100,
        170,
        30,
    ),
    (
        220,
        220,
        0,
    ),
    (
        175,
        116,
        175,
    ),
    (
        250,
        0,
        30,
    ),
    (
        165,
        42,
        42,
    ),
    (
        255,
        77,
        255,
    ),
    (
        255,
        77,
        144,
    ),
]
param_scheduler = [
    dict(begin=0, by_epoch=False, end=500, start_factor=0.1, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=12,
        gamma=0.1,
        milestones=[
            8,
            11,
        ],
        type='MultiStepLR'),
]
resume = False
save_epoch_intervals = 1
test_ann_file = 'annotations/nobackground/test.json'
test_cfg = dict(type='TestLoop')
test_data_prefix = 'images'
test_dataloader = dict(
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    batch_size=1,
    dataset=dict(
        ann_file='annotations/nobackground/test.json',
        backend_args=None,
        data_prefix=dict(img='images'),
        data_root='../WindBlade-30K/',
        metainfo=dict(
            classes=(
                'hole',
                'leaf-opex',
                'corrosion',
                'stain',
                'corrosion-pit',
                'lightning-arrester-miss',
                'degumming',
                'repair',
                'lightning-arrester',
                'teeth',
                'demould',
                'painting-peel-off',
                'sign',
                'crack',
                'dirt',
                'swell',
                'oil',
            ),
            palette=[
                (
                    220,
                    20,
                    60,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    0,
                    0,
                    230,
                ),
                (
                    106,
                    0,
                    228,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    0,
                    0,
                    192,
                ),
                (
                    250,
                    170,
                    30,
                ),
                (
                    100,
                    170,
                    30,
                ),
                (
                    220,
                    220,
                    0,
                ),
                (
                    175,
                    116,
                    175,
                ),
                (
                    250,
                    0,
                    30,
                ),
                (
                    165,
                    42,
                    42,
                ),
                (
                    255,
                    77,
                    255,
                ),
                (
                    255,
                    77,
                    144,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='../WindBlade-30K/annotations/nobackground/test.json',
    backend_args=None,
    classwise=True,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_ann_file = 'annotations/nobackground/train.json'
train_cfg = dict(max_epochs=36, type='EpochBasedTrainLoop', val_interval=1)
train_data_prefix = 'images'
train_dataloader = dict(
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    batch_size=8,
    dataset=dict(
        ann_file='annotations/nobackground/train.json',
        backend_args=None,
        data_prefix=dict(img='images'),
        data_root='../WindBlade-30K/',
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        metainfo=dict(
            classes=(
                'hole',
                'leaf-opex',
                'corrosion',
                'stain',
                'corrosion-pit',
                'lightning-arrester-miss',
                'degumming',
                'repair',
                'lightning-arrester',
                'teeth',
                'demould',
                'painting-peel-off',
                'sign',
                'crack',
                'dirt',
                'swell',
                'oil',
            ),
            palette=[
                (
                    220,
                    20,
                    60,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    0,
                    0,
                    230,
                ),
                (
                    106,
                    0,
                    228,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    0,
                    0,
                    192,
                ),
                (
                    250,
                    170,
                    30,
                ),
                (
                    100,
                    170,
                    30,
                ),
                (
                    220,
                    220,
                    0,
                ),
                (
                    175,
                    116,
                    175,
                ),
                (
                    250,
                    0,
                    30,
                ),
                (
                    165,
                    42,
                    42,
                ),
                (
                    255,
                    77,
                    255,
                ),
                (
                    255,
                    77,
                    144,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=8,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(type='PackDetInputs'),
]
val_ann_file = 'annotations/nobackground/val.json'
val_cfg = dict(type='ValLoop')
val_data_prefix = 'images'
val_dataloader = dict(
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    batch_size=1,
    dataset=dict(
        ann_file='annotations/nobackground/val.json',
        backend_args=None,
        data_prefix=dict(img='images'),
        data_root='../WindBlade-30K/',
        metainfo=dict(
            classes=(
                'hole',
                'leaf-opex',
                'corrosion',
                'stain',
                'corrosion-pit',
                'lightning-arrester-miss',
                'degumming',
                'repair',
                'lightning-arrester',
                'teeth',
                'demould',
                'painting-peel-off',
                'sign',
                'crack',
                'dirt',
                'swell',
                'oil',
            ),
            palette=[
                (
                    220,
                    20,
                    60,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    0,
                    0,
                    230,
                ),
                (
                    106,
                    0,
                    228,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    0,
                    0,
                    192,
                ),
                (
                    250,
                    170,
                    30,
                ),
                (
                    100,
                    170,
                    30,
                ),
                (
                    220,
                    220,
                    0,
                ),
                (
                    175,
                    116,
                    175,
                ),
                (
                    250,
                    0,
                    30,
                ),
                (
                    165,
                    42,
                    42,
                ),
                (
                    255,
                    77,
                    255,
                ),
                (
                    255,
                    77,
                    144,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = [dict(
    ann_file='../WindBlade-30K/annotations/nobackground/val.json',
    backend_args=None,
    classwise=True,
    format_only=False,
    metric='bbox',
    type='CocoMetric'),
    dict(
    type='F1PrecisionRecallMetric',
    ann_file='../WindBlade-30K/annotations/nobackground/val.json'
    )]
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './runs/windturbine_GFLv2/KURGFl'
